name: feature request
description: >-
  Use this form to make a suggestion for https://skins.osuck.net. Your feedback
  helps us improve.
title: "feat(): "
labels:
  - "status: open"
  - "type: feature"
  - "priority: low"
assignees:
  - cyperdark
body:
  - type: textarea
    id: feat-desc
    attributes:
      label: feature description
      description: Describe your idea using simple words. If possible, please attach an image showcasing your idea, it could be a sketch, a real example or a document.
      placeholder: My idea is [..].
    validations:
      required: true
